### ISSUE TITLE
"Create from selected items" returns  errors. My alfred tell me this

### ISSUE THREAD

**Issue by yijinbandouya** [bikenik/alfred-ldoce#2]
![2018-05-15 1 04 36](https://user-images.githubusercontent.com/34211937/40037569-8e0fc18c-5840-11e8-8f65-9839b2d1b62f.png)

**Comment by yijinbandouya** [comment]
The log is below.
[2018-05-15 14:45:39][utility.filter] Processing output of 'output.notification' with arg '{
	"items": [
		{
			"title": "Error: Cannot find module '../input/body.json'",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nError: Cannot find module '../input/body.json'\n    at Object.<anonymous> (/Users/weifengchuiguodexiatian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.E8B7962E-E0F3-4594-BE9B-238C2016A69D/src/api/mydata.js:4:21)\n    at Object.<anonymous> (/Users/weifengchuiguodexiatian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.E8B7962E-E0F3-4594-BE9B-238C2016A69D/src/index.js:14:14)\n```\n\n-\nldoce-Express 1.1.3\nAlfred 3.6.1\ndarwin x64 16.0.0",
				"largetype": "Error: Cannot find module '../input/body.json'\n    at Object.<anonymous> (/Users/weifengchuiguodexiatian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.E8B7962E-E0F3-4594-BE9B-238C2016A69D/src/api/mydata.js:4:21)\n    at Object.<anonymous> (/Users/weifengchuiguodexiatian/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.E8B7962E-E0F3-4594-BE9B-238C2016A69D/src/index.js:14:14)"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
'

**Comment by bikenik** [comment]
I think.. It's happening cause you choose "Create from selected item" but do not select any item (vocabulary entry) before.
 
I'll fix these cases soon with a new update. 
Thanks a lot for your message.

**Comment by yijinbandouya** [comment]
Thanks for your reply.
It is very regrettable. As your answer, I tried again but still failed to add cards. Meanwhile, I found the  "body.json" documents will delete if I choose to "create card from selected senses of word". But when I choose to "⌥ + ↩ — create card from all matching of current query", the document will come back. 
Another problem is when I install ldoce-express workflows 1.1.8, the search is invalid(like below). But the 1.1.3 is valid.
![2018-05-15 5 50 40](https://user-images.githubusercontent.com/34211937/40050185-4bbb6e5c-5869-11e8-97ad-935bfe8aae58.png)
![2018-05-15 5 52 00](https://user-images.githubusercontent.com/34211937/40050191-50d0943a-5869-11e8-8890-1dfb64298bd7.png)

Whatever your idea is very good,  I have never seen who want to connect Alfred with Anki. 
Thanks again for your genius idea！Looking forward to your update.

**Comment by bikenik** [comment]
I try to explain it again for more clarity.
To avoid this error

1. select items or one item
2. press <kbd>⌘ + ↩</kbd>

I tested it quite a long time. And I got this error only occurs after these steps: when I do the second step before the first step.
In other words - when I press  <kbd>⌘ + ↩</kbd>  but have not selected any items to this.

> I found the "body.json" documents will delete if I choose to "create card from selected senses of word".

Everything is as it should be as you say.
"body.json" will be deleted after each set of a new query. And generates again when you **click**  to one or several fields of the query result. **And only after that**, you should press <kbd>⌘ + ↩</kbd> —  to create card from selected senses of word. 

https://youtu.be/MD6wpJJIzHc?t=53

***
> Another problem is when I install ldoce-express workflows 1.1.8, the search is invalid(like below). But the 1.1.3 is valid.

I think you should delete all version from the "Alfred preferences" and install again as
`npm install --global alfred-ldoce`

I tested it with a scratch install and wasn't get this issue. 
If I'll understand why you getting this errors, I'll be writing here.

**Comment by bikenik** [comment]
No problem.
Keyboard (enter/return or ↵) should work also 100%. Check your dependencies of this key with another application. When you activate this or that field from the query you will hear a sound signal (System mac os sound - "Pop")
Glad to could help you.
Happy English!

**Comment by yijinbandouya** [comment]
In the second problem, I have tried several times to reinstall. But my search is always failing to trigger a  valid workflow with the new version. And I check the log. 
#[2018-05-17 09:01:38][ERROR: input.scriptfilter] Code 127: /Users/weifengchuiguodexiatian/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/6BA726D4-6410-40F3-9D9D-9B49C905B554: line 1: ./node_modules/.bin/run-node: No such file or directory
How could I solve the problem？ Thank you very much.

**Comment by bikenik** [comment]
solved [af81d7a](https://github.com/bikenik/alfred-ldoce/commit/af81d7aac039f098adbb5c8fe43633dcfa22f284)

**Comment by yijinbandouya** [comment]
Thank you very much! All problems are solved.
